# Generated by Django 4.1.7 on 2023-03-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_transaction_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
