# Generated by Django 4.1.7 on 2023-03-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_created_at_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request',
            field=models.CharField(default='ASAP', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(default='monsoon', max_length=58),
        ),
    ]
