# Generated by Django 4.1.7 on 2023-03-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_transaction_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(default='optional note', max_length=140),
        ),
    ]
