# Generated by Django 4.1.7 on 2023-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_transaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='passphrase',
            field=models.CharField(default='', max_length=58),
        ),
    ]
