# Generated by Django 4.1.7 on 2023-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_transaction_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset_id',
            field=models.CharField(max_length=50),
        ),
    ]
