# Generated by Django 4.1.7 on 2023-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_transaction_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.CharField(default='', max_length=58),
        ),
    ]
